name: Deploy React App to GitHub Pages Manually

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy build output to /docs
        run: |
          rm -rf docs
          mkdir docs
          cp -r build/* docs/

      - name: Commit and push /docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update GitHub Pages" || echo "No changes to commit"
          git pull
          git push origin master
          
